---
substitutions:
  name: cabtemp8266

esphome:
  name: ${name}

esp8266:
  board: d1_mini

sensor:
  - platform: dht
    model: SI7021
    pin:
      number: D2
      #mode:
      #  input: true
      #  pullup: false
    temperature:
      name: Cabin Office Temp
    humidity:
      name: Cabin Office Humidity
    update_interval: 10s

<<: !include include/pn_pac_default.yaml
#<<: !include include/pw_pac_default.yaml
