---
substitutions:
  name: irt01

esphome:
  name: ${name}

esp8266:
  board: esp8285

remote_receiver:
  pin:
    number: GPIO14
    inverted: true
  dump: all

remote_transmitter:
  pin:
    number: GPIO4
  carrier_duty_percent: 50%
 
text_sensor:
  - platform: homeassistant
    id: Test_RC_Code
    entity_id: input_text.ac_rc_code

button:
  - platform: template
    name: "On/Off"
    on_press:
      - remote_transmitter.transmit_pioneer: 
          rc_code_1: 0x2004
  - platform: template
    name: "Mode"
    on_press:
      - remote_transmitter.transmit_pioneer: 
          rc_code_1: 0x200D
  - platform: template
    name: "Up"
    on_press:
      - remote_transmitter.transmit_pioneer: 
          rc_code_1: 0x2005
  - platform: template
    name: "Down"
    on_press:
      - remote_transmitter.transmit_pioneer: 
          rc_code_1: 0x2001
  - platform: template
    name: "Speed"
    on_press:
      - remote_transmitter.transmit_pioneer: 
          rc_code_1: 0x2006
  - platform: template
    name: "Timer"
    on_press:
      - remote_transmitter.transmit_pioneer: 
          rc_code_1: 0x2000

  - platform: template
    name: "Code from HA"
    on_press:
      - remote_transmitter.transmit_pioneer: 
          rc_code_1: lambda return id(Test_RC_Code).state.c_str();
#<<: !include include/pn_pac_default.yaml
<<: !include include/pw_pac_default.yaml

