---
substitutions:
  name: irt01

esphome:
  name: ${name}

esp8266:
  board: esp8285

remote_receiver:
  pin:
    number: GPIO14
    inverted: true
  dump: all

remote_transmitter:
  pin:
    number: GPIO4
  carrier_duty_percent: 50%

<<: !include include/pn_pac_default.yaml

