---
substitutions:
  name: irt01

#globals:
#  - id: harccode
#    initial_value: '0x2004'
#    type: int

esphome:
  name: ${name}

esp8266:
  board: esp8285

remote_receiver:
  pin:
    number: GPIO14
    inverted: true
  dump: all

remote_transmitter:
  pin:
    number: GPIO4
  carrier_duty_percent: 50%
 
sensor:
  - platform: homeassistant
    id: Test_RC_Code
    entity_id: input_number.ac_rc_number
    #entity_id: input_text.ac_rc_code

button:
  - platform: template
    name: "Cabin AC On/Off"
    on_press:
      - remote_transmitter.transmit_pioneer: 
          rc_code_1: 0x2004
  - platform: template
    name: "Cabin AC Mode"
    on_press:
      - remote_transmitter.transmit_pioneer: 
          rc_code_1: 0x200D
  - platform: template
    name: "Cabin AC Up"
    on_press:
      - remote_transmitter.transmit_pioneer: 
          rc_code_1: 0x2005
  - platform: template
    name: "Cabin AC Down"
    on_press:
      - remote_transmitter.transmit_pioneer: 
          rc_code_1: 0x2001
  - platform: template
    name: "Cabin AC Speed"
    on_press:
      - remote_transmitter.transmit_pioneer: 
          rc_code_1: 0x2006
  - platform: template
    name: "Cabin AC Timer"
    on_press:
      - remote_transmitter.transmit_pioneer: 
          rc_code_1: 0x2000

  - platform: template
    name: "Cabin AC Code from HA"
    on_press:
      #- globals.set:
      #    id: harccode
      #    value: !lambda return int(id(Test_RC_Code).state);
      - remote_transmitter.transmit_pioneer: 
          rc_code_1: !lambda return int(id(Test_RC_Code).state);
          #rc_code_1: !lambda |-
            #ESP_LOGD("lambda","sent %i to trans", id(harccode));
            #ESP_LOGD("lambda","got %i from sensor", id(Test_RC_Code));
            #return id(harccode);


#<<: !include include/pn_pac_default.yaml
<<: !include include/pw_pac_default.yaml
